name: deploy irc

on:
  push:
    branches:
      - master
    paths:
      - '*'
      - modules/shared/**
      - modules/irc/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: sbt irc/assembly
    - uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: sectery
        environment_name: irc-env
        version_label: irc-${{ github.SHA }}
        region: us-east-2
        deployment_package: modules/irc/target/scala-3.1.1/irc.jar
